# Welcome to Jekyll!

# Site settings
title: "Naveen Gudimilla | Portfolio"
email: gudimillanaveen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to My Professional Journey! 🚀 This platform showcases my experiences, 
  skills, and insights as I navigate through the world of technology and innovation. 
  Here, you’ll find my projects, achievements, and thoughts on the latest trends in AI, 
  web development, and business solutions.

  I specialize in AI-driven solutions, UI/UX design, no-code development, and project management. 
  Currently, I'm working on an account system, reward management, and tracking system for a service company, 
  integrating the latest plugins to optimize business processes.  

  Explore my journey, check out my latest projects, and connect with me for collaborations!

github_username: Navireddy369
minimal_mistakes_skin: mint
search: true

# GitHub repository settings
github:
  repository: NaviReddy369/NaviReddy369.github.io  # Make sure this is correct

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Output settings
permalink: /:categories/:title/
#paginate: 5 # Number of posts to show
#paginate_path: /page:num/
timezone: America/New_York # ✅ Set a valid timezone (Example: 'America/New_York')

# Header Navigation
header_pages:
  - projects.md
  - blogs.md
  - about.md

# Include _pages directory
include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Information
author:
  name    : "Naveen Gudimilla"
  avatar  : "/assets/images/displaypic.jpg.png"
  bio     : "IT professional specializing in AI-driven solutions, web development, and project management. Passionate about integrating technology and business to create impactful, data-driven solutions."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://navireddy369.github.io/NaviReddy369.github.io/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/naveen-gudimilla"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NaviReddy369"

# Footer Links
footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://navireddy369.github.io/NaviReddy369.github.io/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/naveen-gudimilla"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NaviReddy369"

# Fixing YAML structure in `defaults`
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: false
      share: true
      related: false

  - scope: # ✅ Corrected indentation here
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Category & Tag Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
